# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'RemoteControl_ios' do
  
    pod 'Masonry'
    
    pod 'SDWebImage'
        
    pod 'AFNetworking'

    pod 'MBProgressHUD'
   
end
